Dispose http connections when the test is over
Signed-off-by: Marcos Candeia <marrcooos@gmail.com>

diff --git a/.github/workflows/dapr-test.yml b/.github/workflows/dapr-test.yml
--- a/.github/workflows/dapr-test.yml
+++ b/.github/workflows/dapr-test.yml
@@ -301,7 +301,7 @@ jobs:
       TEST_OUTPUT_FILE_PREFIX: "test_report"
       PULL_POLICY: IfNotPresent
       TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
-      TEST_E2E_USE_INTERNAL_IP: true
+      TEST_E2E_USE_INTERNAL_IP: false
     strategy:
       fail-fast: false
       matrix:
@@ -402,7 +402,7 @@ jobs:
         run: ./tests/test-infra/setup_${{ env.TEST_CLOUD_ENV }}.sh
         shell: bash
       - name: Setup tailscale subnet router
-        if: env.TEST_PREFIX != ''
+        if: env.TEST_PREFIX != '' && env.TEST_E2E_USE_INTERNAL_IP == 'true'
         run: |
           # Pod and service cidr used by tailscale subnet router
           POD_CIDR=$(kubectl cluster-info dump | grep -m 1 cluster-cidr |grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}/[0-9]{1,3}")
@@ -412,11 +412,16 @@ jobs:
           for i in 1 2 3 4 5; do
             echo "waiting for tailscale pod" && kubectl logs -l app=tailscale -n ${{ env.DAPR_NAMESPACE }} && [[ $(kubectl get pods -l app=tailscale -n ${{ env.DAPR_NAMESPACE }} -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') == "True" ]] && break || sleep 10
           done
+          if [[ $(kubectl get pods -l app=tailscale -n ${{ env.DAPR_NAMESPACE }} -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; then
+            echo "tailscale pod couldn't be ready"
+            exit 1
+          fi
           echo "tailscale pod is now ready"
           sleep 5
           kubectl logs -l app=tailscale -n ${{ env.DAPR_NAMESPACE }}
       - name: Connect to tailscale VPN
         uses: tailscale/github-action@e870a1112fcc1faeeeeea3c1b0ce544e5ad01844
+        if: env.TEST_PREFIX != '' && env.TEST_E2E_USE_INTERNAL_IP == 'true'
         with:
           authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
           version: 1.28.0
